lms/courses/urls.py
from django.urls import path
from . import views
from .views import (CourseUpdateView, CourseDeleteView, LessonCreateView, LessonUpdateView, LessonDeleteView,
                    ModuleCreateView, ModuleUpdateView, ModuleDeleteView)

app_name = 'courses'
urlpatterns = [
    
    # COURSE CRUD URL.
    path(
        '<slug:course_slug>/manage/', 
        views.course_manage, 
        name= 'course_manage'
        ),
    path(
        'create/', 
        views.course_create, 
        name= 'course_create'
        ),
    path(
        '<slug:slug>/update/', 
        CourseUpdateView.as_view(), 
        name= 'course_update'
        ),
    path(
        '<slug:slug>/delete/', 
        CourseDeleteView.as_view(), 
        name= 'course_delete'
        ),

    # MODULE CRUD URL.
    path(
        '<slug:course_slug>/module/create/',
         ModuleCreateView.as_view(), 
         name= 'module_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/update/',
         ModuleUpdateView.as_view(), 
         name= 'module_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/delete/',
         ModuleDeleteView.as_view(), 
         name= 'module_delete'
         ),

    # LESSON CRUD URL.
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/create/', 
         LessonCreateView.as_view(), 
         name= 'lesson_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/update/',
         LessonUpdateView.as_view(), 
         name= 'lesson_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/delete/',
         LessonDeleteView.as_view(), 
         name= 'lesson_delete'
         ),

    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/complete/', 
         views.mark_lesson_completion, 
         name= 'mark_lesson_complete'
         ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/', 
         views.lesson_detail, 
         name= 'lesson_details'
         ),
    
     # main url
    path(
        '<slug:course_slug>/', 
        views.course_detail, 
        name= 'course_details'
        ),
    path(
        '', 
        views.course_list, 
        name= 'course_list'
        ),
    
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # users app.
    path('accounts/', include('users.urls')),
    path('', include('users.urls')),

    # Enrollment app.
    path('enroll/', include('enrollment.urls')),

    # courses app.
    path('courses', include('courses.urls')),

    # Quiz app.
    path('quiz/', include('quiz.urls')),
    
    # Discussion app.
    path('discussion/', include('discussion.urls')),

    # tinymce
    path('tinymce/', include('tinymce.urls')),

    # Django password reset urls.
    path('accounts/password_reset/', 
         auth_view.PasswordResetView.as_view(template_name= 'users/password_reset_form.html'),
         name= 'password_reset'),
        
    path('accounts/password_reset/done/', 
         auth_view.PasswordResetDoneView.as_view(template_name= 'users/password_reset_done.html'),
         name= 'password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', 
         auth_view.PasswordResetConfirmView.as_view(template_name= 'users/password_reset_confirm.html'),
         name= 'password_reset_confirm'),

    path('accounts/reset/done/', 
         auth_view.PasswordResetCompleteView.as_view(template_name= 'users/password_reset_complete.html'),
         name= 'password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATICFILES_DIRS)

lms/users/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name= 'register'),
    path('', views.user_login, name= 'login'),
    path('logout/', views.logout_user, name= 'logout'),
    path('profile/', views.profile, name= 'profile'),
    path('student_dashboard/', views.student_dashboard, name= 'student_dashboard'),
    path('instructor_dashboard/', views.Instructor_dashboard, name= 'instructor_dashboard'),
    path('notifications/read/<int:pk>/', views.mark_notification_as_read, name= 'mark_notification_as_read'),
]

lms/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from courses.models import Course, Lesson
# Create your models here.


class MemberUser(AbstractUser):
    is_student = models.BooleanField(default= False)
    is_instructor = models.BooleanField(default= False)

    wants_to_be_instructor = models.BooleanField(default= False, verbose_name= 'Instructor Request')

    email = models.EmailField(_("email address"), unique=True)
    bio = models.TextField(null= True, blank= True)
    avatar = models.ImageField(null= True, blank= True)
    phone = models.CharField(max_length= 10, null= True, blank= True)


    def __str__(self):
        return self.username


User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE, related_name= 'profile')
    bio = models.TextField(max_length= 500, blank= True)
    profile_pic = models.ImageField(upload_to= 'profile_pics/', default= 'default.jpg', blank= True)

    def __str__(self):
        return f'{self.user.username} Profile'
    

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'notifications')
    message = models.CharField(max_length= 500)
    related_course = models.ForeignKey(Course, on_delete= models.CASCADE, null= True, blank= True)
    related_lesson = models.ForeignKey(Lesson, on_delete= models.CASCADE, null= True, blank= True)

    is_read = models.BooleanField(default= False)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return f"Notification for {self.user.username} : {self.message}"
    
    def absolute_url(self):
        if self.related_lesson:
            return reverse('courses:lesson_details', args=[self.related_lesson.module.course.slug,
                                                           self.related_lesson.module.slug, 
                                                           self.related_lesson.slug])
        elif self.related_course:
            return reverse('courses:course_details', args=[self.related_course.slug])
        
        return '#'
    

class UserLessonCompletion(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE, related_name= 'lesson_completion')

    lesson = models.ForeignKey(Lesson, on_delete= models.CASCADE, related_name= 'user_completions')
    is_completed = models.BooleanField(default= False)
    completed_at = models.DateTimeField(auto_now_add= True)

    class Meta:
        unique_together= ('student', 'lesson')
        ordering = ['completed_at']
        verbose_name_plural = 'User Lesson Completions'

    def __str__(self):
        return f'{self.student.username} completed {self.lesson.title}'

lms/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm

from django.contrib.auth import get_user_model
from .models import MemberUser, Profile
from .services import notify_admin_insrtuctor_request

class MemberUserCreation(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = MemberUser
        fields = UserCreationForm.Meta.fields + ('email', 'is_student', 'is_instructor')
    
    def save(self, commit= True):
        user = super().save(commit= False)
        user.is_student = True
        user.is_instructor = False

        if self.cleaned_data.get('is_instructor'):
            user.wants_to_be_instructor = True
            user.is_student = False

        if commit:
            user.save()
            if user.wants_to_be_instructor:
                notify_admin_insrtuctor_request(user)
        return user
    

class MemberUserChangeForm(UserChangeForm):
    class Meta:
        model = MemberUser
        fields = '__all__'


User = get_user_model()

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic']

lms/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import F, Count, OuterRef, Subquery
from django.db.models.functions import Coalesce
from django.contrib.auth import get_user_model, update_session_auth_hash

from .forms import MemberUserChangeForm, MemberUserCreation, UserUpdateForm, ProfileUpdateForm
from .models import Profile, Notification, UserLessonCompletion
from enrollment.models import Enroll
from courses.models import Course, Lesson
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = MemberUserCreation(request.POST)

        if form.is_valid():
            user= form.save()
            login(request, user)
            messages.success(request, "Registration Successful.")
            return redirect('courses:course_list')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')

    else:
        form = MemberUserCreation()
    
    context = {'form': form, 'page_title': 'Register'}
    return render(request, 'users/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data= request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username= username, password= password)

            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome {username} !.")
                return redirect('courses:course_list')
            else:
                messages.error(request, "Invalid credentials.")
            
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
        
    else:
        form = AuthenticationForm()

    context = {'form': form, 'page_title': 'Login'}
    return render(request, 'users/login.html', context)


def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return redirect('users:login')

@login_required(login_url= 'users:login')
def profile(request):
    user = request.user
    Profile.objects.get_or_create(user= user)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance= user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance= user.profile)

        if 'update_user' in request.POST and user_form.is_valid():
            user_form.save()
            messages.success(request, "Your accounts details are updated successfully.")
            return redirect('users:profile')
        
        elif 'update_profile' in request.POST and profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Your profile details are updated successfully.")
            return redirect('users:profile')
        
    else:
        user_form = UserUpdateForm(instance= user)
        profile_form = ProfileUpdateForm(instance= user.profile)

    enrolled_course = Enroll.objects.filter(student= user)
    instructor_course = Course.objects.filter(instructor= user)

    notifications = Notification.objects.filter(user= request.user).order_by('-created_at')

    section = request.GET.get('section', 'info')
    if section == 'notifications':
        notifications.filter(is_read=False).update(is_read=True)

    unread_notifications_count = notifications.filter(is_read=False).count()

    context ={'user_form': user_form, 'profile_form': profile_form, 
              'enrolled_course': enrolled_course, 'instructor_course': instructor_course, 'page_title': 'profile',
              'notifications': notifications, 'unread_notifications_count': unread_notifications_count}
    
    section = request.GET.get('section', 'info')
    if section == 'security':
        template_name = 'partials/profile_security.html'
    elif section == 'courses':
        template_name = 'partials/profile_courses.html'
    elif section == 'notifications':
        template_name = 'partials/profile_notification.html'
    else:
        template_name = 'users/profile.html'
    return render(request, template_name, context)


# @login_required(login_url= 'users:login')
# def student_dashboard(request):
#     if not request.user.is_student:
#         messages.warning(request, "This page is only for student.")

#         if request.user.is_instructor:
#             return redirect('users:profile')
#         else:
#             return redirect('courses:course_list')
        
#     enrolled_course = Enroll.objects.filter(student= request.user).select_related('course')

#     context= {'enrolled_course': enrolled_course, 'page_title': 'My Learning Dashboard'}
#     return render(request, 'users/stu_dashboard.html', context)

@login_required
def student_dashboard(request):
    if not request.user.is_student:
        messages.warning(request, "This page is only for students.")
        return redirect('users:profile')
    
    # Base queryset for all of the users enrollments.
    enrollments = Enroll.objects.filter(student= request.user)

    # Subquery to count total lessons foe each course.
    total_lessons_sq = Lesson.objects.filter(
        module__course= OuterRef('course')
    ).values('module__course').annotate(count= Count('id')).values('count')

    # Subquery to count completed lessons for user in each course.
    completed_lesson_sq = UserLessonCompletion.objects.filter(
        student= request.user,
        lesson__module__course= OuterRef('course'),
        is_completed= True,
    ).values('lesson__module__course').annotate(count= Count('id')).values('count')

    # Annotate the main queryset with the count from out aubqueries.
    enrollments = enrollments.annotate(
        total_lessons = Coalesce(Subquery(total_lessons_sq), 0),
        completed_lessons = Coalesce(Subquery(completed_lesson_sq), 0),
    ).select_related('course')

    context= {'enrolled_courses': enrollments, 
              'page_title': 'My Learning Dashboard'}
    return render(request, "users/stu_dashboard.html", context)


@login_required(login_url= 'users:login')
def Instructor_dashboard(request):
    if not request.user.is_instructor:
        messages.warning(request, "This page is only for Instructors.")

        if request.user.is_student:
            return redirect('users:student_dashboard')
        else:
            return redirect('courses:course_list')
        
    instructor_courses = Course.objects.filter(instructor= request.user)

    context = {'instructor_course': instructor_courses, 'page_title': 'Instructor Dashboard'}
    return render(request, 'users/ins_dashboard.html', context)


def mark_notification_as_read(request, pk):
    notification = get_object_or_404(Notification, pk= pk)
    notification.is_read= True
    notification.save()
    return redirect(notification.get_absolute_url())

lms/users/templates/users/ins_dashboard.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block content %}

<main>
    <section>
        <div class="dash_container">

            <div class="card-header mb-4">
                <h2 class="dash_title">{{page_title}}</h2>
                <a href="{% url 'courses:course_create' %}" class="btn btn-success">
                    Create New Course
                </a>
            </div>
            

            {% if instructor_course %}
                <div class="course_card_list">

                    {% for course in instructor_course %}
                        <div class="course_card">
                            <h3>{{course.title}}</h3>
                            <p>{{course.description|truncatechars:100}}</p>
                            <p class="instructor">
                                {% if course.is_published %}
                                    <span class="status_publish">Published</span>
                                {% else %}
                                    <span class="status_draft">Draft</span>
                                {% endif %}
                            </p>

                            <div class="card-footer">
                                <span>
                                    <a href="{{course.get_absolute_url}}" class="btn btn-info w-50 mb-2">View Course</a>
                                    <a href="{% url 'courses:course_manage' course.slug %}" class="btn btn-secondary w-50">
                                        Manage
                                    </a>
                                </span>
                                <span>
                                    <a href="{% url 'courses:course_update' course.slug %}" class="edit_btn">Edit</a>
                                    <a href="{% url 'courses:course_delete' course.slug %}" class="del_btn">Delete</a>
                                </span>
                            </div>
                            
                        </div>
                    {% endfor %}

                </div>

            {% else %}

            <p class="no_course_msg">
                You haven't created any Courses yet.
            </p>

            <p class="no_course_msg">
                Click the button above to create Your first course
            </p>

            {% endif %}

        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/login.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<main id="login">
    <section>
        <div class="form_container">
            <h2>{{page_title}}</h2>
            <form action="" method="post"> {% csrf_token %}
                <div class="form_group">
                    <label for="{{form.username.id_for_label}}">Username : </label>
                    {{form.username}}
                </div>
                <div class="form_group">
                    <label for="{{form.password.id_for_label}}">Password : </label>
                    {{form.password}}
                </div>

                <button type="submit" class="btn-primary">Login</button>
            </form>

            <div class="from_link">
                <p class="form_text">Don't have an account?<a href="{% url 'users:register' %}">Register Here</a></p>
                <p class="form_text"><a href="{% url 'password_reset' %}">Forget Your password?</a></p>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/password_reset_complete.html
{% extends 'main.html' %}
{% load static %}

{% block title %} 
Password Reset Complete.
{% endblock title%}

{% block content %}

<main id="p_reset_comp">
    <section>
        <div class="message_container">
            <h2>Password Reset Complete.</h2>
            <p>
                Your password has been successfully set. You can now log in with your new password.
            </p>
            
            <p>
                <a href="{% url 'users:login' %}" class="login_link">Login</a>
            </p>
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/password_reset_confirm.html
{% extends 'main.html' %}
{% load static %}

{% block title %} 
Set a New Password.
{% endblock title%}

{% block content %}

<main id="p_reset_confirm">
    <section>
        <div class="form_container">
            {% if validlink %}
            <h2>Set a New Password.</h2>

            <form action="" method="post"> {% csrf_token %}
                {% if form.no_field_errors %}
                    <div class="alert_alert_danger">
                        {% for error in form.non_field_errors %}
                        <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="form_group">
                    <label for="{{form.new_password1.id_for_label}}">New Password : </label>
                    {{form.new_password1}}
                    {% if form.new_password1.errors %}
                        <ul class="errorlist">
                            {% for error in form.new_password1.errors %}
                            <li>{{error}}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form_group">
                    <label for="{{form.new_password2.id_for_label}}">Confirm Password : </label>
                    {{form.new_password2}}
                    {% if form.new_password2.errors %}
                        <ul class="errorlist">
                            {% for error in form.new_password2.errors %}
                            <li>{{error}}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <button type="submit" class="btn-primary">Set Password</button>
            </form>
        </div>
        <div>
            {% else %}
            <div class="message_container">
                <h2>Invalid Link</h2>
                <p>
                    The Password reset link was invalid, possibly because it has already been used.
                    please request a new password reset.
                </p>
                <a href="{% url 'password_reset' %}">Request a New Password reset</a>
            </div>
            {% endif %}
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/password_reset_done.html
{% extends 'main.html' %}
{% load static %}

{% block title %} 
Password Reset Sent 
{% endblock title%}

{% block content %}

<main id="p_reset_done">
    <section>
        <div class="message_container">
            <h2>Password Reset Email Sent.</h2>
            <p>
                We've emailed you instructions for setting your password, if an account 
                exists with the email you entered.
            </p>
            <p>You should receive them shortly.</p>

            <p>
                If you don't receive an email, please make sure you've entered the 
                email address you registered with, and check your spam folder.
            </p>
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/password_reset_form.html
{% extends 'main.html' %}
{% load static %}

{% block title %} 
Forget your Password? 
{% endblock title%}

{% block content %}

<main id="p_reset_form">
    <section>
        <div class="form_container">
            <h2>Forget Your Password?</h2>
            <p class="form_text">
                Enter your email address below and we'll email you instructions for setting a new one.
            </p>

            <form action="" method="post"> {% csrf_token %}
                <div class="form_group">
                    <label for="{{form.email.id_for_label}}">Email Address : </label>
                    {{form.email}}
                </div>
                <button type="submit" class="btn-primary">Reset My Password</button>
            </form>
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/profile.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

{% block title %}
    {{page_title}}
{% endblock title %}

<main>

    <section>
        <div>
            <h2>{{request.user.username}}'s Profile</h2>
            <p>Bio : {{request.user.profile.bio}}</p>

            <div>
                <h3>Account Details</h3>
                <form action="" method="post"> {% csrf_token %}
                    <h4>Personal information</h4>
                    {{user_form.as_p}}
                    <button type="submit" name="update_user">Update Details</button>
                </form>
            </div><hr>

            <div>
                <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
                    <h4>About Me</h4>
                    {{profile_form.as_p}}
                    <button type="submit" name="update_profile">Update Profile</button>
                </form>
            </div><hr>

            {% if request.user.is_authenticated %}
                <h4>My Course (as Instructor)</h4>
                {% for course in instructor_course %}
                    <p>
                        <a href="{% url 'courses:course_details' course.slug %}">{{course.title}}</a>
                    </p>
                {% empty %}
                    <p>You haven't created any course yet.</p>
                {% endfor %}
                    
                <h4>My Course (as Student)</h4>
                {% for enrolled in enrolled_course %}
                    <p>
                        <a href="{% url 'courses:course_details' enrolled.course.slug %}">{{enrolled.course.title}}</a>
                    </p>
                {% empty %}
                    <p>You are not enrolled in any course yet.</p>
                {% endfor %}
            {% endif %}
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<main id="register">
    <section>
        <div class="form_container">
            <h1>{{page_title}}</h1>
            <form action="" method="post"> {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Register</button>
            </form><br>

            <div class="from_link">
                Already having an account?<a href="{% url 'users:login' %}">Login Here</a>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

lms/users/templates/users/stu_dashboard.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section class="container mt-4">
    <h2 class="mb-2">{{page_title}}</h2>
    {% if enrolled_courses %}
        <div class="row">

            {% for enroll in enrolled_courses %}
                <div class="col-md-6 col-lg-4 mb-4">

                    <div class="card ">
                        {% if enroll.course.thumbnail %}
                        <img src="{{enroll.course.thumbnail.url}}" class="card-img-top" 
                        alt="{{enroll.course.title}} thumbnail">
                        {% endif %}
                    </div>

                    <div class="card-body d-flex flex-column ">
                        <h5 class="card-title"> {{enroll.course.title}} </h5>
                        <p class="card-text text-muted">
                            by {{enroll.course.instructor.username}}
                        </p>

                        {% if enroll.total_lessons >= 0 %}
                            
                            <div class="progress mb-2" style="height: 20px;">

                                <div class="progress-bar" role="progressbar"
                                aria-valuenow="{{enroll.progress_percentage|floatformat:0}}"
                                aria-valuemin="0"
                                aria-valuemax="100"
                                style="width: {{enroll.progress_percentage|floatformat:0}}%;">

                                {{enroll.progress_percentage|floatformat:0}}

                                </div>

                            </div>
                            <p class="card-text">
                                <small> 
                                    {{enroll.completed_lessons}} of {{enroll.total_lessons}} lessons completed.
                                </small>
                            </p>
                        
                        {% else %}
                            <p class="card-text">
                                <small>This course has no lessons yet.</small>
                            </p>
                        {% endif %}

                        <div class="mt-6">
                            {% with next_lesson=enroll.get_next_lesson %}
                                {% if next_lesson %}
                                    <a href="{{next_lesson.get_absolute_url}}" class="btn btn-primary">
                                        Continue Learning
                                    </a>
                                {% else %}
                                    <a href="{{enroll.course.get_absolute_url}}" class="btn btn-success">
                                        Course Completed! Review
                                    </a>
                                {% endif %}
                            {% endwith %}
                        </div>

                    </div>

                </div>
            {% endfor %}

        </div>
    {% else %}

        <div class="alert alert-info">
            You are not currently enrolled in any courses. <a href="{% url 'courses:course_list' %}"
            class="alert-link"> Browse course
            </a> to get started.
        </div>

    {% endif %}
</section>

{% endblock content %}