lms/courses/urls.py
from django.urls import path
from . import views
from .views import (CourseUpdateView, CourseDeleteView, LessonCreateView, LessonUpdateView, LessonDeleteView,
                    ModuleCreateView, ModuleUpdateView, ModuleDeleteView)

app_name = 'courses'
urlpatterns = [
    
    # COURSE CRUD URL.
    path(
        '<slug:course_slug>/manage/', 
        views.course_manage, 
        name= 'course_manage'
        ),
    path(
        'create/', 
        views.course_create, 
        name= 'course_create'
        ),
    path(
        '<slug:slug>/update/', 
        CourseUpdateView.as_view(), 
        name= 'course_update'
        ),
    path(
        '<slug:slug>/delete/', 
        CourseDeleteView.as_view(), 
        name= 'course_delete'
        ),

    # MODULE CRUD URL.
    path(
        '<slug:course_slug>/module/create/',
         ModuleCreateView.as_view(), 
         name= 'module_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/update/',
         ModuleUpdateView.as_view(), 
         name= 'module_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/delete/',
         ModuleDeleteView.as_view(), 
         name= 'module_delete'
         ),

    # LESSON CRUD URL.
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/create/', 
         LessonCreateView.as_view(), 
         name= 'lesson_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/update/',
         LessonUpdateView.as_view(), 
         name= 'lesson_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/delete/',
         LessonDeleteView.as_view(), 
         name= 'lesson_delete'
         ),

    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/complete/', 
         views.mark_lesson_completion, 
         name= 'mark_lesson_complete'
         ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/', 
         views.lesson_detail, 
         name= 'lesson_details'
         ),
    
     # main url
    path(
        '<slug:course_slug>/', 
        views.course_detail, 
        name= 'course_details'
        ),
    path(
        '', 
        views.course_list, 
        name= 'course_list'
        ),
    
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # users app.
    path('accounts/', include('users.urls')),
    path('', include('users.urls')),

    # Enrollment app.
    path('enroll/', include('enrollment.urls')),

    # courses app.
    path('courses', include('courses.urls')),

    # Quiz app.
    path('quiz/', include('quiz.urls')),
    
    # Discussion app.
    path('discussion/', include('discussion.urls')),

    # tinymce
    path('tinymce/', include('tinymce.urls')),

    # Django password reset urls.
    path('accounts/password_reset/', 
         auth_view.PasswordResetView.as_view(template_name= 'users/password_reset_form.html'),
         name= 'password_reset'),
        
    path('accounts/password_reset/done/', 
         auth_view.PasswordResetDoneView.as_view(template_name= 'users/password_reset_done.html'),
         name= 'password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', 
         auth_view.PasswordResetConfirmView.as_view(template_name= 'users/password_reset_confirm.html'),
         name= 'password_reset_confirm'),

    path('accounts/reset/done/', 
         auth_view.PasswordResetCompleteView.as_view(template_name= 'users/password_reset_complete.html'),
         name= 'password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATICFILES_DIRS)

lms/users/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name= 'register'),
    path('', views.user_login, name= 'login'),
    path('logout/', views.logout_user, name= 'logout'),
    path('profile/', views.profile, name= 'profile'),
    path('student_dashboard/', views.student_dashboard, name= 'student_dashboard'),
    path('instructor_dashboard/', views.Instructor_dashboard, name= 'instructor_dashboard'),
    path('notifications/read/<int:pk>/', views.mark_notification_as_read, name= 'mark_notification_as_read'),
]

lms/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduNova</title>
    <link rel="stylesheet" href="{% static 'style/lms.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>

    {{form.media}}

</head>
<body>
    <header>
        {% include 'nav.html' %}
    </header><br><hr><br>
    
    <main>
        {% if messages %}
            <ul class="messages">
                {% for i in messages %}
                    <li class="{{i.tags}}">{{i}}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% block content %}

        {% endblock content %}
    </main>

    <footer>
        <p id="foot">&copy; 2025 Anirudh Projects</p>
    </footer>
</body>
</html>

lms/templates/nav.html
{% load static %}
<nav class="navbar navbar-dark bg-dark border-bottom border-body fixed-top">
    
    <div class="container-fluid">
        
        <h1 class="navbar-brand">EduNova</h1>

        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                                        aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        
        {% if unread_notifications_count == 0 %}
            <span class="badge bg-danger rounded-pill">
                {{unread_notifications_count}}
            </span>
        {% endif %}
        </button>
    
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" 
                                                        aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header d-flex justify-content-between">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">

                    <a href="{% url 'users:profile' %}?section=notifications " class="nav-link">
                        EduNova
                    </a>
                {% if unread_notifications_count >= 0 %}
                    <span class="badge bg-danger rounded-pill">
                        {{unread_notifications_count}}
                    </span>
                {% endif %}
                </h5>
            

                <button class="btn-close btn-close-white" type="button" data-bs-dismiss="offcanvas" 
                        aria-label="Close"></button>
            </div>
              
            <div class="offcanvas-body">
                
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a href="{% url 'courses:course_list' %}" class="nav-link">
                            Courses</a>
                    </li>
                    
                {% if request.user.is_authenticated %}     
                    {% if request.user.is_student %}

                    <li class="nav-item">
                        <a href="{% url 'users:student_dashboard' %}" class="nav-link">
                            My Learning</a>
                    </li>

                    {% elif request.user.is_instructor %}

                    <li class="nav-item">
                        <a href="{% url 'users:instructor_dashboard' %}" class="nav-link">
                            My Dashboard</a>
                    </li>

                    {% endif %}

                    <li class="nav-item">
                        <a href="{% url 'users:profile' %}" class="nav-link">
                            Profile</a>
                        <a href="{% url 'users:logout' %}" class="nav-link">
                            Logout</a>
                    </li>
                    
                {% else %} 

                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">
                            Register</a>
                        <a href="{% url 'users:login' %}" class="nav-link">
                            Login</a>
                    </li>

                </ul>
                {% endif %}
            </div>
            
        </div>
    </div>
</nav>